name: '🔄 CI'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: '🪄 Lint | ${{ matrix.command.name }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command:
          - { name: '📦 Composer', command: 'lint:composer' }
          - { name: '🔍 PHPStan', command: 'lint:phpstan -- --no-progress' }
          - { name: '🪶 PHP CS Fixer', command: "lint:php-cs-fixer -- --format=checkstyle | sed -n '/^<?xml/,$p' | cs2pr" }
          - { name: '🏠 Rector', command: 'lint:rector -- --no-progress-bar' }

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: '⚙️ Prepare environment'
        uses: $/.github/actions/setup

      - name: '${{ matrix.command.name }} validate'
        run: task ${{ matrix.command.command }}

  test:
    name: '♻️ Test | PHP ${{ matrix.php }}'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.4', '8.5']

    steps:
      - name: '🛎 Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: '⚙️ Prepare environment'
        uses: $/.github/actions/setup
        with:
          php: ${{ matrix.php }}

      - name: '🔬 Run tests'
        run: task test -- --no-progress
